name: Firebase Hosting deployment on merge to production branch

on:
  push:
    branches:
      - production

env:
  VITE_APP_ICON: "${{ secrets.APP_ICON }}"
  VITE_APP_TITLE: "${{ secrets.APP_TITLE }}"
  VITE_APP_DESCRIPTION: "${{ secrets.APP_DESCRIPTION }}"
  VITE_APP_OG_IMAGE: "${{ secrets.APP_OG_IMAGE }}"
  VITE_APP_THEME_PRIMARY_MAIN: "${{ secrets.APP_THEME_PRIMARY_MAIN }}"
  VITE_APP_THEME_SECONDARY_MAIN: "${{ secrets.APP_THEME_SECONDARY_MAIN }}"

jobs:
  firebase-hosting-deployment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm test
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          target: "portfolio"
